gestor_homepage:
    path:     /
    defaults: { _controller: gestorBundle:Empresa:all}

all_empresa:
    path:     /empresa/all
    defaults: { _controller: gestorBundle:Empresa:all}

nueva_empresa:
    path:     /empresa/new
    defaults: { _controller: gestorBundle:Empresa:new}

all_alumno:
    path:     /alumno/all
    defaults: { _controller: gestorBundle:Alumno:all}

api_alumnos_get:
    path:     /api/empresas
    defaults: { _controller: gestorBundle:Api:empresasGet }
    methods: [GET]

api_alumnos_post:
    path:     /api/empresas
    defaults: { _controller: gestorBundle:Api:empresasPost }
    methods: [POST]
